// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: auction-srv/auction-srv.proto

package auction_srv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAuctionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemName       string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	StartTimestamp uint64                 `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   uint64                 `protobuf:"varint,3,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAuctionRequest) Reset() {
	*x = CreateAuctionRequest{}
	mi := &file_auction_srv_auction_srv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionRequest) ProtoMessage() {}

func (x *CreateAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_srv_auction_srv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionRequest.ProtoReflect.Descriptor instead.
func (*CreateAuctionRequest) Descriptor() ([]byte, []int) {
	return file_auction_srv_auction_srv_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAuctionRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CreateAuctionRequest) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *CreateAuctionRequest) GetEndTimestamp() uint64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

type Auction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Item           string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	StartTimestamp uint64                 `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   uint64                 `protobuf:"varint,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Status         bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_auction_srv_auction_srv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_auction_srv_auction_srv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_auction_srv_auction_srv_proto_rawDescGZIP(), []int{1}
}

func (x *Auction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Auction) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Auction) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *Auction) GetEndTimestamp() uint64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *Auction) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GetActiveAuctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAuctionsRequest) Reset() {
	*x = GetActiveAuctionsRequest{}
	mi := &file_auction_srv_auction_srv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAuctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAuctionsRequest) ProtoMessage() {}

func (x *GetActiveAuctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_srv_auction_srv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAuctionsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveAuctionsRequest) Descriptor() ([]byte, []int) {
	return file_auction_srv_auction_srv_proto_rawDescGZIP(), []int{2}
}

type GetActiveAuctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auctions      []*Auction             `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAuctionsResponse) Reset() {
	*x = GetActiveAuctionsResponse{}
	mi := &file_auction_srv_auction_srv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAuctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAuctionsResponse) ProtoMessage() {}

func (x *GetActiveAuctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_srv_auction_srv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAuctionsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveAuctionsResponse) Descriptor() ([]byte, []int) {
	return file_auction_srv_auction_srv_proto_rawDescGZIP(), []int{3}
}

func (x *GetActiveAuctionsResponse) GetAuctions() []*Auction {
	if x != nil {
		return x.Auctions
	}
	return nil
}

var File_auction_srv_auction_srv_proto protoreflect.FileDescriptor

const file_auction_srv_auction_srv_proto_rawDesc = "" +
	"\n" +
	"\x1dauction-srv/auction-srv.proto\x12\vauction_srv\"\x81\x01\n" +
	"\x14CreateAuctionRequest\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12'\n" +
	"\x0fstart_timestamp\x18\x02 \x01(\x04R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x03 \x01(\x04R\fendTimestamp\"\x93\x01\n" +
	"\aAuction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x04R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x04 \x01(\x04R\fendTimestamp\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\"\x1a\n" +
	"\x18GetActiveAuctionsRequest\"M\n" +
	"\x19GetActiveAuctionsResponse\x120\n" +
	"\bauctions\x18\x01 \x03(\v2\x14.auction_srv.AuctionR\bauctions2\xbe\x01\n" +
	"\x0eAuctionService\x12H\n" +
	"\rCreateAuction\x12!.auction_srv.CreateAuctionRequest\x1a\x14.auction_srv.Auction\x12b\n" +
	"\x11GetActiveAuctions\x12%.auction_srv.GetActiveAuctionsRequest\x1a&.auction_srv.GetActiveAuctionsResponseB\x1eZ\x1cgateway/proto-go/auction_srvb\x06proto3"

var (
	file_auction_srv_auction_srv_proto_rawDescOnce sync.Once
	file_auction_srv_auction_srv_proto_rawDescData []byte
)

func file_auction_srv_auction_srv_proto_rawDescGZIP() []byte {
	file_auction_srv_auction_srv_proto_rawDescOnce.Do(func() {
		file_auction_srv_auction_srv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_srv_auction_srv_proto_rawDesc), len(file_auction_srv_auction_srv_proto_rawDesc)))
	})
	return file_auction_srv_auction_srv_proto_rawDescData
}

var file_auction_srv_auction_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auction_srv_auction_srv_proto_goTypes = []any{
	(*CreateAuctionRequest)(nil),      // 0: auction_srv.CreateAuctionRequest
	(*Auction)(nil),                   // 1: auction_srv.Auction
	(*GetActiveAuctionsRequest)(nil),  // 2: auction_srv.GetActiveAuctionsRequest
	(*GetActiveAuctionsResponse)(nil), // 3: auction_srv.GetActiveAuctionsResponse
}
var file_auction_srv_auction_srv_proto_depIdxs = []int32{
	1, // 0: auction_srv.GetActiveAuctionsResponse.auctions:type_name -> auction_srv.Auction
	0, // 1: auction_srv.AuctionService.CreateAuction:input_type -> auction_srv.CreateAuctionRequest
	2, // 2: auction_srv.AuctionService.GetActiveAuctions:input_type -> auction_srv.GetActiveAuctionsRequest
	1, // 3: auction_srv.AuctionService.CreateAuction:output_type -> auction_srv.Auction
	3, // 4: auction_srv.AuctionService.GetActiveAuctions:output_type -> auction_srv.GetActiveAuctionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auction_srv_auction_srv_proto_init() }
func file_auction_srv_auction_srv_proto_init() {
	if File_auction_srv_auction_srv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_srv_auction_srv_proto_rawDesc), len(file_auction_srv_auction_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auction_srv_auction_srv_proto_goTypes,
		DependencyIndexes: file_auction_srv_auction_srv_proto_depIdxs,
		MessageInfos:      file_auction_srv_auction_srv_proto_msgTypes,
	}.Build()
	File_auction_srv_auction_srv_proto = out.File
	file_auction_srv_auction_srv_proto_goTypes = nil
	file_auction_srv_auction_srv_proto_depIdxs = nil
}
