# Use the official Golang image as the base
FROM rust:1.91-alpine AS builder

RUN apk add --no-cache protobuf protobuf-dev

# Install necessary build tools and dependencies for Alpine
RUN apk add --no-cache musl-dev gcc

COPY proto-definitions /proto-definitions

WORKDIR /build

# Copy Cargo.toml and Cargo.lock first to leverage Docker cache for dependencies
COPY ./auction_system .

# Build the final release binary
RUN cargo build --release -p auction-srv

# Stage 2: Runner
FROM alpine:latest AS final

# Install any runtime dependencies if required (e.g., if your Rust app uses dynamic libraries)
# For a fully static Rust binary, this might not be needed.
# RUN apk add --no-cache libssl1.1 # Example for a common dependency

# Copy the compiled binary from the builder stage
COPY --from=builder /build/target/release/auction-srv ./bin/auction-srv

# Define the command to run your application
CMD ["./bin/auction-srv"]