// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *EventRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AuctionId     uint32                 `protobuf:"varint,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *EventResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventResponse) GetAuctionId() uint32 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *EventResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type AuctionSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AuctionId     []uint32               `protobuf:"varint,2,rep,packed,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionSubscribeRequest) Reset() {
	*x = AuctionSubscribeRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionSubscribeRequest) ProtoMessage() {}

func (x *AuctionSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionSubscribeRequest.ProtoReflect.Descriptor instead.
func (*AuctionSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionSubscribeRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *AuctionSubscribeRequest) GetAuctionId() []uint32 {
	if x != nil {
		return x.AuctionId
	}
	return nil
}

type AuctionSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionSubscribeResponse) Reset() {
	*x = AuctionSubscribeResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionSubscribeResponse) ProtoMessage() {}

func (x *AuctionSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionSubscribeResponse.ProtoReflect.Descriptor instead.
func (*AuctionSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *AuctionSubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AuctionUnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AuctionId     []uint32               `protobuf:"varint,2,rep,packed,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionUnsubscribeRequest) Reset() {
	*x = AuctionUnsubscribeRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionUnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionUnsubscribeRequest) ProtoMessage() {}

func (x *AuctionUnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionUnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*AuctionUnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *AuctionUnsubscribeRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *AuctionUnsubscribeRequest) GetAuctionId() []uint32 {
	if x != nil {
		return x.AuctionId
	}
	return nil
}

type AuctionUnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionUnsubscribeResponse) Reset() {
	*x = AuctionUnsubscribeResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionUnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionUnsubscribeResponse) ProtoMessage() {}

func (x *AuctionUnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionUnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*AuctionUnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *AuctionUnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gateway_gateway_proto protoreflect.FileDescriptor

const file_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/gateway.proto\x12\agateway\"+\n" +
	"\fEventRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\"a\n" +
	"\rEventResponse\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\rR\tauctionId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"U\n" +
	"\x17AuctionSubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x03(\rR\tauctionId\"4\n" +
	"\x18AuctionSubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x19AuctionUnsubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x03(\rR\tauctionId\"6\n" +
	"\x1aAuctionUnsubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x85\x02\n" +
	"\vEventStream\x12>\n" +
	"\vStreamStart\x12\x15.gateway.EventRequest\x1a\x16.gateway.EventResponse0\x01\x12W\n" +
	"\x10AuctionSubscribe\x12 .gateway.AuctionSubscribeRequest\x1a!.gateway.AuctionSubscribeResponse\x12]\n" +
	"\x12AuctionUnsubscribe\x12\".gateway.AuctionUnsubscribeRequest\x1a#.gateway.AuctionUnsubscribeResponseB\x1aZ\x18gateway/proto-go/gatewayb\x06proto3"

var (
	file_gateway_gateway_proto_rawDescOnce sync.Once
	file_gateway_gateway_proto_rawDescData []byte
)

func file_gateway_gateway_proto_rawDescGZIP() []byte {
	file_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)))
	})
	return file_gateway_gateway_proto_rawDescData
}

var file_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gateway_gateway_proto_goTypes = []any{
	(*EventRequest)(nil),               // 0: gateway.EventRequest
	(*EventResponse)(nil),              // 1: gateway.EventResponse
	(*AuctionSubscribeRequest)(nil),    // 2: gateway.AuctionSubscribeRequest
	(*AuctionSubscribeResponse)(nil),   // 3: gateway.AuctionSubscribeResponse
	(*AuctionUnsubscribeRequest)(nil),  // 4: gateway.AuctionUnsubscribeRequest
	(*AuctionUnsubscribeResponse)(nil), // 5: gateway.AuctionUnsubscribeResponse
}
var file_gateway_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.EventStream.StreamStart:input_type -> gateway.EventRequest
	2, // 1: gateway.EventStream.AuctionSubscribe:input_type -> gateway.AuctionSubscribeRequest
	4, // 2: gateway.EventStream.AuctionUnsubscribe:input_type -> gateway.AuctionUnsubscribeRequest
	1, // 3: gateway.EventStream.StreamStart:output_type -> gateway.EventResponse
	3, // 4: gateway.EventStream.AuctionSubscribe:output_type -> gateway.AuctionSubscribeResponse
	5, // 5: gateway.EventStream.AuctionUnsubscribe:output_type -> gateway.AuctionUnsubscribeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_gateway_proto_init() }
func file_gateway_gateway_proto_init() {
	if File_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_proto_msgTypes,
	}.Build()
	File_gateway_gateway_proto = out.File
	file_gateway_gateway_proto_goTypes = nil
	file_gateway_gateway_proto_depIdxs = nil
}
