// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: gateway/gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStream_StreamStart_FullMethodName        = "/gateway.EventStream/StreamStart"
	EventStream_AuctionSubscribe_FullMethodName   = "/gateway.EventStream/AuctionSubscribe"
	EventStream_AuctionUnsubscribe_FullMethodName = "/gateway.EventStream/AuctionUnsubscribe"
)

// EventStreamClient is the client API for EventStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventStreamClient interface {
	StreamStart(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error)
	AuctionSubscribe(ctx context.Context, in *AuctionSubscribeRequest, opts ...grpc.CallOption) (*AuctionSubscribeResponse, error)
	AuctionUnsubscribe(ctx context.Context, in *AuctionUnsubscribeRequest, opts ...grpc.CallOption) (*AuctionUnsubscribeResponse, error)
}

type eventStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamClient(cc grpc.ClientConnInterface) EventStreamClient {
	return &eventStreamClient{cc}
}

func (c *eventStreamClient) StreamStart(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStream_ServiceDesc.Streams[0], EventStream_StreamStart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventRequest, EventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_StreamStartClient = grpc.ServerStreamingClient[EventResponse]

func (c *eventStreamClient) AuctionSubscribe(ctx context.Context, in *AuctionSubscribeRequest, opts ...grpc.CallOption) (*AuctionSubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuctionSubscribeResponse)
	err := c.cc.Invoke(ctx, EventStream_AuctionSubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStreamClient) AuctionUnsubscribe(ctx context.Context, in *AuctionUnsubscribeRequest, opts ...grpc.CallOption) (*AuctionUnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuctionUnsubscribeResponse)
	err := c.cc.Invoke(ctx, EventStream_AuctionUnsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStreamServer is the server API for EventStream service.
// All implementations must embed UnimplementedEventStreamServer
// for forward compatibility.
type EventStreamServer interface {
	StreamStart(*EventRequest, grpc.ServerStreamingServer[EventResponse]) error
	AuctionSubscribe(context.Context, *AuctionSubscribeRequest) (*AuctionSubscribeResponse, error)
	AuctionUnsubscribe(context.Context, *AuctionUnsubscribeRequest) (*AuctionUnsubscribeResponse, error)
	mustEmbedUnimplementedEventStreamServer()
}

// UnimplementedEventStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStreamServer struct{}

func (UnimplementedEventStreamServer) StreamStart(*EventRequest, grpc.ServerStreamingServer[EventResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamStart not implemented")
}
func (UnimplementedEventStreamServer) AuctionSubscribe(context.Context, *AuctionSubscribeRequest) (*AuctionSubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuctionSubscribe not implemented")
}
func (UnimplementedEventStreamServer) AuctionUnsubscribe(context.Context, *AuctionUnsubscribeRequest) (*AuctionUnsubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuctionUnsubscribe not implemented")
}
func (UnimplementedEventStreamServer) mustEmbedUnimplementedEventStreamServer() {}
func (UnimplementedEventStreamServer) testEmbeddedByValue()                     {}

// UnsafeEventStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStreamServer will
// result in compilation errors.
type UnsafeEventStreamServer interface {
	mustEmbedUnimplementedEventStreamServer()
}

func RegisterEventStreamServer(s grpc.ServiceRegistrar, srv EventStreamServer) {
	// If the following call panics, it indicates UnimplementedEventStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStream_ServiceDesc, srv)
}

func _EventStream_StreamStart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStreamServer).StreamStart(m, &grpc.GenericServerStream[EventRequest, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_StreamStartServer = grpc.ServerStreamingServer[EventResponse]

func _EventStream_AuctionSubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStreamServer).AuctionSubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStream_AuctionSubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStreamServer).AuctionSubscribe(ctx, req.(*AuctionSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStream_AuctionUnsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionUnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStreamServer).AuctionUnsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStream_AuctionUnsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStreamServer).AuctionUnsubscribe(ctx, req.(*AuctionUnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventStream_ServiceDesc is the grpc.ServiceDesc for EventStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.EventStream",
	HandlerType: (*EventStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuctionSubscribe",
			Handler:    _EventStream_AuctionSubscribe_Handler,
		},
		{
			MethodName: "AuctionUnsubscribe",
			Handler:    _EventStream_AuctionUnsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStart",
			Handler:       _EventStream_StreamStart_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway/gateway.proto",
}
