// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *EventRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AuctionId     uint32                 `protobuf:"varint,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *EventResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventResponse) GetAuctionId() uint32 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *EventResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type AuctionSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AuctionId     []uint32               `protobuf:"varint,2,rep,packed,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionSubscribeRequest) Reset() {
	*x = AuctionSubscribeRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionSubscribeRequest) ProtoMessage() {}

func (x *AuctionSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionSubscribeRequest.ProtoReflect.Descriptor instead.
func (*AuctionSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionSubscribeRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *AuctionSubscribeRequest) GetAuctionId() []uint32 {
	if x != nil {
		return x.AuctionId
	}
	return nil
}

type AuctionSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionSubscribeResponse) Reset() {
	*x = AuctionSubscribeResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionSubscribeResponse) ProtoMessage() {}

func (x *AuctionSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionSubscribeResponse.ProtoReflect.Descriptor instead.
func (*AuctionSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *AuctionSubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AuctionUnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AuctionId     []uint32               `protobuf:"varint,2,rep,packed,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionUnsubscribeRequest) Reset() {
	*x = AuctionUnsubscribeRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionUnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionUnsubscribeRequest) ProtoMessage() {}

func (x *AuctionUnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionUnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*AuctionUnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *AuctionUnsubscribeRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *AuctionUnsubscribeRequest) GetAuctionId() []uint32 {
	if x != nil {
		return x.AuctionId
	}
	return nil
}

type AuctionUnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionUnsubscribeResponse) Reset() {
	*x = AuctionUnsubscribeResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionUnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionUnsubscribeResponse) ProtoMessage() {}

func (x *AuctionUnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionUnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*AuctionUnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *AuctionUnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Auction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Item           string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	StartTimestamp uint64                 `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   uint64                 `protobuf:"varint,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Status         bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_gateway_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *Auction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Auction) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Auction) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *Auction) GetEndTimestamp() uint64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *Auction) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GetActiveAuctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAuctionsRequest) Reset() {
	*x = GetActiveAuctionsRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAuctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAuctionsRequest) ProtoMessage() {}

func (x *GetActiveAuctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAuctionsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveAuctionsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{7}
}

type GetActiveAuctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auctions      []*Auction             `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAuctionsResponse) Reset() {
	*x = GetActiveAuctionsResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAuctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAuctionsResponse) ProtoMessage() {}

func (x *GetActiveAuctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAuctionsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveAuctionsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *GetActiveAuctionsResponse) GetAuctions() []*Auction {
	if x != nil {
		return x.Auctions
	}
	return nil
}

type CreateAuctionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemName       string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	StartTimestamp uint64                 `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   uint64                 `protobuf:"varint,3,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAuctionRequest) Reset() {
	*x = CreateAuctionRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionRequest) ProtoMessage() {}

func (x *CreateAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionRequest.ProtoReflect.Descriptor instead.
func (*CreateAuctionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAuctionRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CreateAuctionRequest) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *CreateAuctionRequest) GetEndTimestamp() uint64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

type CreateAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionResponse) Reset() {
	*x = CreateAuctionResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionResponse) ProtoMessage() {}

func (x *CreateAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionResponse.ProtoReflect.Descriptor instead.
func (*CreateAuctionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAuctionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     uint32                 `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ClientId      uint32                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Valid         bool                   `protobuf:"varint,6,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBidRequest) Reset() {
	*x = CreateBidRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBidRequest) ProtoMessage() {}

func (x *CreateBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBidRequest.ProtoReflect.Descriptor instead.
func (*CreateBidRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBidRequest) GetAuctionId() uint32 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *CreateBidRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateBidRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateBidRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CreateBidRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateBidRequest) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type CreateBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBidResponse) Reset() {
	*x = CreateBidResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBidResponse) ProtoMessage() {}

func (x *CreateBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBidResponse.ProtoReflect.Descriptor instead.
func (*CreateBidResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBidResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gateway_gateway_proto protoreflect.FileDescriptor

const file_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/gateway.proto\x12\agateway\"+\n" +
	"\fEventRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\"a\n" +
	"\rEventResponse\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\rR\tauctionId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"U\n" +
	"\x17AuctionSubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x03(\rR\tauctionId\"4\n" +
	"\x18AuctionSubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x19AuctionUnsubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x03(\rR\tauctionId\"6\n" +
	"\x1aAuctionUnsubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x93\x01\n" +
	"\aAuction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x04R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x04 \x01(\x04R\fendTimestamp\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\"\x1a\n" +
	"\x18GetActiveAuctionsRequest\"I\n" +
	"\x19GetActiveAuctionsResponse\x12,\n" +
	"\bauctions\x18\x01 \x03(\v2\x10.gateway.AuctionR\bauctions\"\x81\x01\n" +
	"\x14CreateAuctionRequest\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12'\n" +
	"\x0fstart_timestamp\x18\x02 \x01(\x04R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x03 \x01(\x04R\fendTimestamp\"1\n" +
	"\x15CreateAuctionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb7\x01\n" +
	"\x10CreateBidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\rR\tauctionId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\rR\bclientId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\tR\tpublicKey\x12\x14\n" +
	"\x05valid\x18\x06 \x01(\bR\x05valid\"-\n" +
	"\x11CreateBidResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x85\x02\n" +
	"\vEventStream\x12>\n" +
	"\vStreamStart\x12\x15.gateway.EventRequest\x1a\x16.gateway.EventResponse0\x01\x12W\n" +
	"\x10AuctionSubscribe\x12 .gateway.AuctionSubscribeRequest\x1a!.gateway.AuctionSubscribeResponse\x12]\n" +
	"\x12AuctionUnsubscribe\x12\".gateway.AuctionUnsubscribeRequest\x1a#.gateway.AuctionUnsubscribeResponse2\xbc\x01\n" +
	"\x0eAuctionService\x12Z\n" +
	"\x11GetActiveAuctions\x12!.gateway.GetActiveAuctionsRequest\x1a\".gateway.GetActiveAuctionsResponse\x12N\n" +
	"\rCreateAuction\x12\x1d.gateway.CreateAuctionRequest\x1a\x1e.gateway.CreateAuctionResponse2P\n" +
	"\n" +
	"BidService\x12B\n" +
	"\tCreateBid\x12\x19.gateway.CreateBidRequest\x1a\x1a.gateway.CreateBidResponseB\x1aZ\x18gateway/proto-go/gatewayb\x06proto3"

var (
	file_gateway_gateway_proto_rawDescOnce sync.Once
	file_gateway_gateway_proto_rawDescData []byte
)

func file_gateway_gateway_proto_rawDescGZIP() []byte {
	file_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)))
	})
	return file_gateway_gateway_proto_rawDescData
}

var file_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gateway_gateway_proto_goTypes = []any{
	(*EventRequest)(nil),               // 0: gateway.EventRequest
	(*EventResponse)(nil),              // 1: gateway.EventResponse
	(*AuctionSubscribeRequest)(nil),    // 2: gateway.AuctionSubscribeRequest
	(*AuctionSubscribeResponse)(nil),   // 3: gateway.AuctionSubscribeResponse
	(*AuctionUnsubscribeRequest)(nil),  // 4: gateway.AuctionUnsubscribeRequest
	(*AuctionUnsubscribeResponse)(nil), // 5: gateway.AuctionUnsubscribeResponse
	(*Auction)(nil),                    // 6: gateway.Auction
	(*GetActiveAuctionsRequest)(nil),   // 7: gateway.GetActiveAuctionsRequest
	(*GetActiveAuctionsResponse)(nil),  // 8: gateway.GetActiveAuctionsResponse
	(*CreateAuctionRequest)(nil),       // 9: gateway.CreateAuctionRequest
	(*CreateAuctionResponse)(nil),      // 10: gateway.CreateAuctionResponse
	(*CreateBidRequest)(nil),           // 11: gateway.CreateBidRequest
	(*CreateBidResponse)(nil),          // 12: gateway.CreateBidResponse
}
var file_gateway_gateway_proto_depIdxs = []int32{
	6,  // 0: gateway.GetActiveAuctionsResponse.auctions:type_name -> gateway.Auction
	0,  // 1: gateway.EventStream.StreamStart:input_type -> gateway.EventRequest
	2,  // 2: gateway.EventStream.AuctionSubscribe:input_type -> gateway.AuctionSubscribeRequest
	4,  // 3: gateway.EventStream.AuctionUnsubscribe:input_type -> gateway.AuctionUnsubscribeRequest
	7,  // 4: gateway.AuctionService.GetActiveAuctions:input_type -> gateway.GetActiveAuctionsRequest
	9,  // 5: gateway.AuctionService.CreateAuction:input_type -> gateway.CreateAuctionRequest
	11, // 6: gateway.BidService.CreateBid:input_type -> gateway.CreateBidRequest
	1,  // 7: gateway.EventStream.StreamStart:output_type -> gateway.EventResponse
	3,  // 8: gateway.EventStream.AuctionSubscribe:output_type -> gateway.AuctionSubscribeResponse
	5,  // 9: gateway.EventStream.AuctionUnsubscribe:output_type -> gateway.AuctionUnsubscribeResponse
	8,  // 10: gateway.AuctionService.GetActiveAuctions:output_type -> gateway.GetActiveAuctionsResponse
	10, // 11: gateway.AuctionService.CreateAuction:output_type -> gateway.CreateAuctionResponse
	12, // 12: gateway.BidService.CreateBid:output_type -> gateway.CreateBidResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_gateway_proto_init() }
func file_gateway_gateway_proto_init() {
	if File_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_proto_msgTypes,
	}.Build()
	File_gateway_gateway_proto = out.File
	file_gateway_gateway_proto_goTypes = nil
	file_gateway_gateway_proto_depIdxs = nil
}
