// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: payment-int-srv/payment-int-srv.proto

package payment_int_srv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentInternalService_UpdatePayment_FullMethodName = "/payment_int_srv.PaymentInternalService/UpdatePayment"
)

// PaymentInternalServiceClient is the client API for PaymentInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentInternalServiceClient interface {
	UpdatePayment(ctx context.Context, in *UpdatePaymentRequest, opts ...grpc.CallOption) (*UpdatePaymentResponse, error)
}

type paymentInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentInternalServiceClient(cc grpc.ClientConnInterface) PaymentInternalServiceClient {
	return &paymentInternalServiceClient{cc}
}

func (c *paymentInternalServiceClient) UpdatePayment(ctx context.Context, in *UpdatePaymentRequest, opts ...grpc.CallOption) (*UpdatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentInternalService_UpdatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentInternalServiceServer is the server API for PaymentInternalService service.
// All implementations must embed UnimplementedPaymentInternalServiceServer
// for forward compatibility.
type PaymentInternalServiceServer interface {
	UpdatePayment(context.Context, *UpdatePaymentRequest) (*UpdatePaymentResponse, error)
	mustEmbedUnimplementedPaymentInternalServiceServer()
}

// UnimplementedPaymentInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentInternalServiceServer struct{}

func (UnimplementedPaymentInternalServiceServer) UpdatePayment(context.Context, *UpdatePaymentRequest) (*UpdatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePayment not implemented")
}
func (UnimplementedPaymentInternalServiceServer) mustEmbedUnimplementedPaymentInternalServiceServer() {
}
func (UnimplementedPaymentInternalServiceServer) testEmbeddedByValue() {}

// UnsafePaymentInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentInternalServiceServer will
// result in compilation errors.
type UnsafePaymentInternalServiceServer interface {
	mustEmbedUnimplementedPaymentInternalServiceServer()
}

func RegisterPaymentInternalServiceServer(s grpc.ServiceRegistrar, srv PaymentInternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentInternalService_ServiceDesc, srv)
}

func _PaymentInternalService_UpdatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentInternalServiceServer).UpdatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentInternalService_UpdatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentInternalServiceServer).UpdatePayment(ctx, req.(*UpdatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentInternalService_ServiceDesc is the grpc.ServiceDesc for PaymentInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment_int_srv.PaymentInternalService",
	HandlerType: (*PaymentInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePayment",
			Handler:    _PaymentInternalService_UpdatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment-int-srv/payment-int-srv.proto",
}
