# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gateway_pb2 as gateway__pb2


class EventStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamStart = channel.unary_stream(
                '/gateway.EventStream/StreamStart',
                request_serializer=gateway__pb2.EventRequest.SerializeToString,
                response_deserializer=gateway__pb2.EventResponse.FromString,
                )
        self.AuctionSubscribe = channel.unary_unary(
                '/gateway.EventStream/AuctionSubscribe',
                request_serializer=gateway__pb2.AuctionSubscribeRequest.SerializeToString,
                response_deserializer=gateway__pb2.AuctionSubscribeResponse.FromString,
                )
        self.AuctionUnsubscribe = channel.unary_unary(
                '/gateway.EventStream/AuctionUnsubscribe',
                request_serializer=gateway__pb2.AuctionUnsubscribeRequest.SerializeToString,
                response_deserializer=gateway__pb2.AuctionUnsubscribeResponse.FromString,
                )


class EventStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuctionSubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuctionUnsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamStart': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStart,
                    request_deserializer=gateway__pb2.EventRequest.FromString,
                    response_serializer=gateway__pb2.EventResponse.SerializeToString,
            ),
            'AuctionSubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.AuctionSubscribe,
                    request_deserializer=gateway__pb2.AuctionSubscribeRequest.FromString,
                    response_serializer=gateway__pb2.AuctionSubscribeResponse.SerializeToString,
            ),
            'AuctionUnsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.AuctionUnsubscribe,
                    request_deserializer=gateway__pb2.AuctionUnsubscribeRequest.FromString,
                    response_serializer=gateway__pb2.AuctionUnsubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.EventStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/gateway.EventStream/StreamStart',
            gateway__pb2.EventRequest.SerializeToString,
            gateway__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuctionSubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.EventStream/AuctionSubscribe',
            gateway__pb2.AuctionSubscribeRequest.SerializeToString,
            gateway__pb2.AuctionSubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuctionUnsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.EventStream/AuctionUnsubscribe',
            gateway__pb2.AuctionUnsubscribeRequest.SerializeToString,
            gateway__pb2.AuctionUnsubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AuctionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActiveAuctions = channel.unary_unary(
                '/gateway.AuctionService/GetActiveAuctions',
                request_serializer=gateway__pb2.GetActiveAuctionsRequest.SerializeToString,
                response_deserializer=gateway__pb2.GetActiveAuctionsResponse.FromString,
                )
        self.CreateAuction = channel.unary_unary(
                '/gateway.AuctionService/CreateAuction',
                request_serializer=gateway__pb2.CreateAuctionRequest.SerializeToString,
                response_deserializer=gateway__pb2.CreateAuctionResponse.FromString,
                )


class AuctionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActiveAuctions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuctionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActiveAuctions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveAuctions,
                    request_deserializer=gateway__pb2.GetActiveAuctionsRequest.FromString,
                    response_serializer=gateway__pb2.GetActiveAuctionsResponse.SerializeToString,
            ),
            'CreateAuction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAuction,
                    request_deserializer=gateway__pb2.CreateAuctionRequest.FromString,
                    response_serializer=gateway__pb2.CreateAuctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.AuctionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuctionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActiveAuctions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.AuctionService/GetActiveAuctions',
            gateway__pb2.GetActiveAuctionsRequest.SerializeToString,
            gateway__pb2.GetActiveAuctionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.AuctionService/CreateAuction',
            gateway__pb2.CreateAuctionRequest.SerializeToString,
            gateway__pb2.CreateAuctionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BidServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBid = channel.unary_unary(
                '/gateway.BidService/CreateBid',
                request_serializer=gateway__pb2.CreateBidRequest.SerializeToString,
                response_deserializer=gateway__pb2.CreateBidResponse.FromString,
                )


class BidServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BidServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBid': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBid,
                    request_deserializer=gateway__pb2.CreateBidRequest.FromString,
                    response_serializer=gateway__pb2.CreateBidResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.BidService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BidService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.BidService/CreateBid',
            gateway__pb2.CreateBidRequest.SerializeToString,
            gateway__pb2.CreateBidResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
