// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: payment-int-srv/payment-int-srv.proto

package payment_int_srv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest) Reset() {
	*x = UpdatePaymentRequest{}
	mi := &file_payment_int_srv_payment_int_srv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest) ProtoMessage() {}

func (x *UpdatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_int_srv_payment_int_srv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_int_srv_payment_int_srv_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type UpdatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentResponse) Reset() {
	*x = UpdatePaymentResponse{}
	mi := &file_payment_int_srv_payment_int_srv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentResponse) ProtoMessage() {}

func (x *UpdatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_int_srv_payment_int_srv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_int_srv_payment_int_srv_proto_rawDescGZIP(), []int{1}
}

var File_payment_int_srv_payment_int_srv_proto protoreflect.FileDescriptor

const file_payment_int_srv_payment_int_srv_proto_rawDesc = "" +
	"\n" +
	"%payment-int-srv/payment-int-srv.proto\x12\x0fpayment_int_srv\"5\n" +
	"\x14UpdatePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\x17\n" +
	"\x15UpdatePaymentResponse2x\n" +
	"\x16PaymentInternalService\x12^\n" +
	"\rUpdatePayment\x12%.payment_int_srv.UpdatePaymentRequest\x1a&.payment_int_srv.UpdatePaymentResponseB\"Z gateway/proto-go/payment-int-srvb\x06proto3"

var (
	file_payment_int_srv_payment_int_srv_proto_rawDescOnce sync.Once
	file_payment_int_srv_payment_int_srv_proto_rawDescData []byte
)

func file_payment_int_srv_payment_int_srv_proto_rawDescGZIP() []byte {
	file_payment_int_srv_payment_int_srv_proto_rawDescOnce.Do(func() {
		file_payment_int_srv_payment_int_srv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_int_srv_payment_int_srv_proto_rawDesc), len(file_payment_int_srv_payment_int_srv_proto_rawDesc)))
	})
	return file_payment_int_srv_payment_int_srv_proto_rawDescData
}

var file_payment_int_srv_payment_int_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_payment_int_srv_payment_int_srv_proto_goTypes = []any{
	(*UpdatePaymentRequest)(nil),  // 0: payment_int_srv.UpdatePaymentRequest
	(*UpdatePaymentResponse)(nil), // 1: payment_int_srv.UpdatePaymentResponse
}
var file_payment_int_srv_payment_int_srv_proto_depIdxs = []int32{
	0, // 0: payment_int_srv.PaymentInternalService.UpdatePayment:input_type -> payment_int_srv.UpdatePaymentRequest
	1, // 1: payment_int_srv.PaymentInternalService.UpdatePayment:output_type -> payment_int_srv.UpdatePaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_int_srv_payment_int_srv_proto_init() }
func file_payment_int_srv_payment_int_srv_proto_init() {
	if File_payment_int_srv_payment_int_srv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_int_srv_payment_int_srv_proto_rawDesc), len(file_payment_int_srv_payment_int_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_int_srv_payment_int_srv_proto_goTypes,
		DependencyIndexes: file_payment_int_srv_payment_int_srv_proto_depIdxs,
		MessageInfos:      file_payment_int_srv_payment_int_srv_proto_msgTypes,
	}.Build()
	File_payment_int_srv_payment_int_srv_proto = out.File
	file_payment_int_srv_payment_int_srv_proto_goTypes = nil
	file_payment_int_srv_payment_int_srv_proto_depIdxs = nil
}
