// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: payment-ext-srv/payment-ext-srv.proto

package payment_ext_srv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentExternalService_CreateTransaction_FullMethodName = "/payment_external_srv.PaymentExternalService/CreateTransaction"
	PaymentExternalService_GetTransactions_FullMethodName   = "/payment_external_srv.PaymentExternalService/GetTransactions"
	PaymentExternalService_PayTransaction_FullMethodName    = "/payment_external_srv.PaymentExternalService/PayTransaction"
)

// PaymentExternalServiceClient is the client API for PaymentExternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentExternalServiceClient interface {
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error)
	PayTransaction(ctx context.Context, in *PayTransactionRequest, opts ...grpc.CallOption) (*PayTransactionResponse, error)
}

type paymentExternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentExternalServiceClient(cc grpc.ClientConnInterface) PaymentExternalServiceClient {
	return &paymentExternalServiceClient{cc}
}

func (c *paymentExternalServiceClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentExternalService_CreateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentExternalServiceClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionsResponse)
	err := c.cc.Invoke(ctx, PaymentExternalService_GetTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentExternalServiceClient) PayTransaction(ctx context.Context, in *PayTransactionRequest, opts ...grpc.CallOption) (*PayTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentExternalService_PayTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentExternalServiceServer is the server API for PaymentExternalService service.
// All implementations must embed UnimplementedPaymentExternalServiceServer
// for forward compatibility.
type PaymentExternalServiceServer interface {
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error)
	GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error)
	PayTransaction(context.Context, *PayTransactionRequest) (*PayTransactionResponse, error)
	mustEmbedUnimplementedPaymentExternalServiceServer()
}

// UnimplementedPaymentExternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentExternalServiceServer struct{}

func (UnimplementedPaymentExternalServiceServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedPaymentExternalServiceServer) GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedPaymentExternalServiceServer) PayTransaction(context.Context, *PayTransactionRequest) (*PayTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayTransaction not implemented")
}
func (UnimplementedPaymentExternalServiceServer) mustEmbedUnimplementedPaymentExternalServiceServer() {
}
func (UnimplementedPaymentExternalServiceServer) testEmbeddedByValue() {}

// UnsafePaymentExternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentExternalServiceServer will
// result in compilation errors.
type UnsafePaymentExternalServiceServer interface {
	mustEmbedUnimplementedPaymentExternalServiceServer()
}

func RegisterPaymentExternalServiceServer(s grpc.ServiceRegistrar, srv PaymentExternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentExternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentExternalService_ServiceDesc, srv)
}

func _PaymentExternalService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentExternalServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentExternalService_CreateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentExternalServiceServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentExternalService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentExternalServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentExternalService_GetTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentExternalServiceServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentExternalService_PayTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentExternalServiceServer).PayTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentExternalService_PayTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentExternalServiceServer).PayTransaction(ctx, req.(*PayTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentExternalService_ServiceDesc is the grpc.ServiceDesc for PaymentExternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentExternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment_external_srv.PaymentExternalService",
	HandlerType: (*PaymentExternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransaction",
			Handler:    _PaymentExternalService_CreateTransaction_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _PaymentExternalService_GetTransactions_Handler,
		},
		{
			MethodName: "PayTransaction",
			Handler:    _PaymentExternalService_PayTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment-ext-srv/payment-ext-srv.proto",
}
