// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: payment-ext-srv/payment-ext-srv.proto

package payment_ext_srv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Callback      string                 `protobuf:"bytes,2,opt,name=callback,proto3" json:"callback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_payment_ext_srv_payment_ext_srv_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentLink   string                 `protobuf:"bytes,3,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_payment_ext_srv_payment_ext_srv_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateTransactionResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        int64                  `protobuf:"varint,4,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	Callbacl      string                 `protobuf:"bytes,5,opt,name=callbacl,proto3" json:"callbacl,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_payment_ext_srv_payment_ext_srv_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Transaction) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

func (x *Transaction) GetCallbacl() string {
	if x != nil {
		return x.Callbacl
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_payment_ext_srv_payment_ext_srv_proto_rawDescGZIP(), []int{3}
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_payment_ext_srv_payment_ext_srv_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type PayTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayTransactionRequest) Reset() {
	*x = PayTransactionRequest{}
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayTransactionRequest) ProtoMessage() {}

func (x *PayTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayTransactionRequest.ProtoReflect.Descriptor instead.
func (*PayTransactionRequest) Descriptor() ([]byte, []int) {
	return file_payment_ext_srv_payment_ext_srv_proto_rawDescGZIP(), []int{5}
}

func (x *PayTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PayTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayTransactionResponse) Reset() {
	*x = PayTransactionResponse{}
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayTransactionResponse) ProtoMessage() {}

func (x *PayTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_ext_srv_payment_ext_srv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayTransactionResponse.ProtoReflect.Descriptor instead.
func (*PayTransactionResponse) Descriptor() ([]byte, []int) {
	return file_payment_ext_srv_payment_ext_srv_proto_rawDescGZIP(), []int{6}
}

func (x *PayTransactionResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_payment_ext_srv_payment_ext_srv_proto protoreflect.FileDescriptor

const file_payment_ext_srv_payment_ext_srv_proto_rawDesc = "" +
	"\n" +
	"%payment-ext-srv/payment-ext-srv.proto\x12\x14payment_external_srv\"N\n" +
	"\x18CreateTransactionRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bcallback\x18\x02 \x01(\tR\bcallback\"}\n" +
	"\x19CreateTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12!\n" +
	"\fpayment_link\x18\x03 \x01(\tR\vpaymentLink\"\xa1\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\apaid_at\x18\x04 \x01(\x03R\x06paidAt\x12\x1a\n" +
	"\bcallbacl\x18\x05 \x01(\tR\bcallbacl\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x18\n" +
	"\x16GetTransactionsRequest\"`\n" +
	"\x17GetTransactionsResponse\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.payment_external_srv.TransactionR\ftransactions\">\n" +
	"\x15PayTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"0\n" +
	"\x16PayTransactionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status2\xeb\x02\n" +
	"\x16PaymentExternalService\x12t\n" +
	"\x11CreateTransaction\x12..payment_external_srv.CreateTransactionRequest\x1a/.payment_external_srv.CreateTransactionResponse\x12n\n" +
	"\x0fGetTransactions\x12,.payment_external_srv.GetTransactionsRequest\x1a-.payment_external_srv.GetTransactionsResponse\x12k\n" +
	"\x0ePayTransaction\x12+.payment_external_srv.PayTransactionRequest\x1a,.payment_external_srv.PayTransactionResponseB\"Z gateway/proto-go/payment-ext-srvb\x06proto3"

var (
	file_payment_ext_srv_payment_ext_srv_proto_rawDescOnce sync.Once
	file_payment_ext_srv_payment_ext_srv_proto_rawDescData []byte
)

func file_payment_ext_srv_payment_ext_srv_proto_rawDescGZIP() []byte {
	file_payment_ext_srv_payment_ext_srv_proto_rawDescOnce.Do(func() {
		file_payment_ext_srv_payment_ext_srv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_ext_srv_payment_ext_srv_proto_rawDesc), len(file_payment_ext_srv_payment_ext_srv_proto_rawDesc)))
	})
	return file_payment_ext_srv_payment_ext_srv_proto_rawDescData
}

var file_payment_ext_srv_payment_ext_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_payment_ext_srv_payment_ext_srv_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),  // 0: payment_external_srv.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 1: payment_external_srv.CreateTransactionResponse
	(*Transaction)(nil),               // 2: payment_external_srv.Transaction
	(*GetTransactionsRequest)(nil),    // 3: payment_external_srv.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),   // 4: payment_external_srv.GetTransactionsResponse
	(*PayTransactionRequest)(nil),     // 5: payment_external_srv.PayTransactionRequest
	(*PayTransactionResponse)(nil),    // 6: payment_external_srv.PayTransactionResponse
}
var file_payment_ext_srv_payment_ext_srv_proto_depIdxs = []int32{
	2, // 0: payment_external_srv.GetTransactionsResponse.transactions:type_name -> payment_external_srv.Transaction
	0, // 1: payment_external_srv.PaymentExternalService.CreateTransaction:input_type -> payment_external_srv.CreateTransactionRequest
	3, // 2: payment_external_srv.PaymentExternalService.GetTransactions:input_type -> payment_external_srv.GetTransactionsRequest
	5, // 3: payment_external_srv.PaymentExternalService.PayTransaction:input_type -> payment_external_srv.PayTransactionRequest
	1, // 4: payment_external_srv.PaymentExternalService.CreateTransaction:output_type -> payment_external_srv.CreateTransactionResponse
	4, // 5: payment_external_srv.PaymentExternalService.GetTransactions:output_type -> payment_external_srv.GetTransactionsResponse
	6, // 6: payment_external_srv.PaymentExternalService.PayTransaction:output_type -> payment_external_srv.PayTransactionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_ext_srv_payment_ext_srv_proto_init() }
func file_payment_ext_srv_payment_ext_srv_proto_init() {
	if File_payment_ext_srv_payment_ext_srv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_ext_srv_payment_ext_srv_proto_rawDesc), len(file_payment_ext_srv_payment_ext_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_ext_srv_payment_ext_srv_proto_goTypes,
		DependencyIndexes: file_payment_ext_srv_payment_ext_srv_proto_depIdxs,
		MessageInfos:      file_payment_ext_srv_payment_ext_srv_proto_msgTypes,
	}.Build()
	File_payment_ext_srv_payment_ext_srv_proto = out.File
	file_payment_ext_srv_payment_ext_srv_proto_goTypes = nil
	file_payment_ext_srv_payment_ext_srv_proto_depIdxs = nil
}
