// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: bid-srv/bid-srv.proto

package bid_srv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     uint32                 `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ClientId      uint32                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Valid         bool                   `protobuf:"varint,6,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBidRequest) Reset() {
	*x = CreateBidRequest{}
	mi := &file_bid_srv_bid_srv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBidRequest) ProtoMessage() {}

func (x *CreateBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bid_srv_bid_srv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBidRequest.ProtoReflect.Descriptor instead.
func (*CreateBidRequest) Descriptor() ([]byte, []int) {
	return file_bid_srv_bid_srv_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBidRequest) GetAuctionId() uint32 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *CreateBidRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateBidRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateBidRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CreateBidRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateBidRequest) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type CreateBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBidResponse) Reset() {
	*x = CreateBidResponse{}
	mi := &file_bid_srv_bid_srv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBidResponse) ProtoMessage() {}

func (x *CreateBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bid_srv_bid_srv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBidResponse.ProtoReflect.Descriptor instead.
func (*CreateBidResponse) Descriptor() ([]byte, []int) {
	return file_bid_srv_bid_srv_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBidResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_bid_srv_bid_srv_proto protoreflect.FileDescriptor

const file_bid_srv_bid_srv_proto_rawDesc = "" +
	"\n" +
	"\x15bid-srv/bid-srv.proto\x12\abid_srv\"\xb7\x01\n" +
	"\x10CreateBidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\rR\tauctionId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\rR\bclientId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\tR\tpublicKey\x12\x14\n" +
	"\x05valid\x18\x06 \x01(\bR\x05valid\"-\n" +
	"\x11CreateBidResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2P\n" +
	"\n" +
	"BidService\x12B\n" +
	"\tCreateBid\x12\x19.bid_srv.CreateBidRequest\x1a\x1a.bid_srv.CreateBidResponseB\x1aZ\x18gateway/proto-go/bid_srvb\x06proto3"

var (
	file_bid_srv_bid_srv_proto_rawDescOnce sync.Once
	file_bid_srv_bid_srv_proto_rawDescData []byte
)

func file_bid_srv_bid_srv_proto_rawDescGZIP() []byte {
	file_bid_srv_bid_srv_proto_rawDescOnce.Do(func() {
		file_bid_srv_bid_srv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bid_srv_bid_srv_proto_rawDesc), len(file_bid_srv_bid_srv_proto_rawDesc)))
	})
	return file_bid_srv_bid_srv_proto_rawDescData
}

var file_bid_srv_bid_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bid_srv_bid_srv_proto_goTypes = []any{
	(*CreateBidRequest)(nil),  // 0: bid_srv.CreateBidRequest
	(*CreateBidResponse)(nil), // 1: bid_srv.CreateBidResponse
}
var file_bid_srv_bid_srv_proto_depIdxs = []int32{
	0, // 0: bid_srv.BidService.CreateBid:input_type -> bid_srv.CreateBidRequest
	1, // 1: bid_srv.BidService.CreateBid:output_type -> bid_srv.CreateBidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bid_srv_bid_srv_proto_init() }
func file_bid_srv_bid_srv_proto_init() {
	if File_bid_srv_bid_srv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bid_srv_bid_srv_proto_rawDesc), len(file_bid_srv_bid_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bid_srv_bid_srv_proto_goTypes,
		DependencyIndexes: file_bid_srv_bid_srv_proto_depIdxs,
		MessageInfos:      file_bid_srv_bid_srv_proto_msgTypes,
	}.Build()
	File_bid_srv_bid_srv_proto = out.File
	file_bid_srv_bid_srv_proto_goTypes = nil
	file_bid_srv_bid_srv_proto_depIdxs = nil
}
